name: Auto Tweet Scraper

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每2天 UTC时间0点运行（东京时间早上9点）
  workflow_dispatch:       # 允许手动触发（可选）

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  # 安装依赖库

      - name: Verify Secrets and Environment Variables
        run: |
          echo "GCP_CREDENTIALS: ${GCP_CREDENTIALS}"  # 打印凭证内容（谨慎使用）

      - name: Create credentials file directly from secret
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > credentials.json  # 使用 GitHub Secrets 直接生成凭证文件
          echo "GOOGLE_APPLICATION_CREDENTIALS=credentials.json" >> $GITHUB_ENV  # 设置环境变量

      - name: Run tweet fetcher
        run: python main.py  # 运行爬虫脚本