name: Auto Tweet Scraper

on:
  schedule:
    - cron: '0 0 */2 * *'  
  workflow_dispatch: 
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  # 安装依赖库

      - name: Print all environment variables for debugging
        run: env  

      - name: Create credentials file
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > capable-sled-456409-b6-8f3c678b6683.json  # 创建凭证文件
          echo "GOOGLE_APPLICATION_CREDENTIALS=capable-sled-456409-b6-8f3c678b6683.json" >> $GITHUB_ENV  # 设置环境变量

      - name: Check if credentials file exists
        run: |
          ls -alh capable-sled-456409-b6-8f3c678b6683.json  # 确认文件是否创建

      - name: Run tweet fetcher
        run: python main.py  # 运行爬虫脚本