name: Auto Tweet Scraper

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每2天 UTC时间0点运行（东京时间早上9点）
  workflow_dispatch:       # 允许手动触发（可选）

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Install Google Cloud SDK
        run: |
          echo "Installing Google Cloud SDK..."
          curl -sSL https://sdk.cloud.google.com | bash  
          source $HOME/google-cloud-sdk/path.bash.inc

      - name: Authenticate using Google Cloud SDK
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=- 
          gcloud config set project capable-sled-456409-b6  

      - name: Run tweet fetcher
        run: python main.py 